apiVersion: batch/v1
kind: CronJob
metadata:
  name: scrape
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 86400
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
          - name: battle-eu
            image: abome40k/albion-scraper:battles
            command:
            - python
            - scrape_starter.py
            - -server europe
            - -apitype BATTLES
          - name: events-eu
            image: abome40k/albion-scraper:battles
            command: ["python"]
            args:
              - scrape_starter.py
              - -server europe
              - -apitype EVENTS
          restartPolicy: Never
