apiVersion: apps/v1
kind: Deployment
metadata:
  name: evp-am
  labels:
    app: evp-am
spec:
  replicas: 20
  selector:
    matchLabels:
      app: evp-am
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: evp-am
    spec:
      hostAliases:
      - ip: "192.168.88.131"
        hostnames:
        - "dbserver.lan"
      containers:
      - name: evp-eu
        image: abome40k/albion-scraper:battles
        imagePullPolicy: Always
        command:  ["python"]
        args:
          - ev_processor_starter.py
          - -server
          - america
