apiVersion: batch/v1
kind: CronJob
metadata:
  name: scrape
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 86400
      activeDeadlineSeconds: 300
      template:
        spec:
          containers:
          - name: events-eu
            image: abome40k/albion-scraper:battles
            imagePullPolicy: Always
            command:  ["python"]
            args:
              - scrape_starter.py
              - -server
              - europe
              - -apitype
              - EVENTS
          - name: battlle-eu
            image: abome40k/albion-scraper:battles
            imagePullPolicy: Always
            command:  ["python"]
            args:
              - scrape_starter.py
              - -server
              - europe
              - -apitype
              - BATTLES
          restartPolicy: Never
