name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: checkout
      uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: abome40k
        password: ${{ secrets.DOCKER }}    
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3        
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        file: ./Docker/scrape-battles.dockerfile
        tags: abome40k/albion-scraper:battles
        build-args: VERSION= ${{ github.head_ref }}.${{ github.sha }}
